name: Update package versions

on:
  workflow_dispatch:
  schedule:
    - cron: '45 */6 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: 'registry.fedoraproject.org/fedora-minimal:latest'

    steps:
      - name: Prepare
        run: |
          microdnf -y install --nodocs --setopt=install_weak_deps=0 \
            git-core rpm-build curl jq rpmdevtools findutils

      - uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run update scripts
        run: |
          find . -name "update.sh" -exec chmod +x {} \;
          find . -name "update.sh" -execdir {} \;
